
class StyleConstants {
  //
  FONT_SIZE = 20;


  FONT_WEIGHT = 500;


  FULL_PERCENT = '100%';


  TEXT_FONT_SIZE = 25;


  TEXT_HEIGHT = '24vp';


  TEXT_INPUT_HEIGHT = '7%';


  TEXT_INPUT_WIDTH = '93%';


  TEXT_MARGIN_BOTTOM = '3%';


  TEXT_MARGIN_LEFT = '10%';


  LETTER_SPACING = '1.58';


  MARGIN_TOP = '12%';


  MARGIN_BOTTOM_SMALL = '6%';


  MARGIN_BOTTOM_BIG = '250vp';


  BUTTON_HEIGHT = '6%';


  BUTTON_WIDTH = '87%';


  BUTTON_MARGIN_BOTTOM = '24vp';
}

export default new StyleConstants();